export const UPDATE_TABLE_DATA = 'UPDATE_TABLE_DATA';
export const UPDATE_MSG = 'UPDATE_MSG';
//待派车
export const UPDATE_READY='UPDATE_READY';
export const ADD_ORDER="ADD_ORDER";
export const SWITCH_ORDER_CACHE="SWITCH_ORDER_CACHE";
export const TOGGLE_PICK="TOGGLE_PICK";
export const ADD_PICKED="ADD_PICKED";
export const REMOVE_PICKED="REMOVE_PICKED";
export const DELETE_PICKED="DELETE_PICKED";

